### ISSUE TITLE
tm_g_gh_spaghettiplot will have all x ticks and labels

### ISSUE THREAD

**Issue by feiyis1** [insightsengineering/teal.goshawk#219] opened 2023-06-15 23:15 UTC
### Feature description

**Request**: Is it possible to have the x ticks in red circles where there are no records (or data points) not displayed in the spaghetti plot? 

![spaghetti_plot](https://github.com/insightsengineering/teal.goshawk/assets/127898767/3dd5ff4a-4bf1-4a11-b0aa-a16d8b31139e)

**Observations**: The line plot with the same filter setting only displays x ticks where there are records (or data points).

![line_plot](https://github.com/insightsengineering/teal.goshawk/assets/127898767/627dadd0-35e9-4da8-b2d4-7e82877778a6)

I also explored the source code of [tm_g_gh_spaghettiplot](https://code.roche.com/nest/insights-engineering/teal.goshawk/-/blob/main/R/tm_g_gh_spaghettiplot.R)  and [tm_g_gh_lineplot](https://code.roche.com/nest/insights-engineering/teal.goshawk/-/blob/main/R/tm_g_gh_lineplot.R) and found some differences between them which may cause the differences in spaghetti plot and line plot display just from my understanding. Not sure if they are the true cause. Please see two chunks of code below. Hope this is helpful. Thank you.
**_tm_g_gh_lineplot:_** subset the data based on xtick
```ruby
# Row 728-744
private_qenv <- teal.code::eval_code(
  object = private_qenv,
  code = bquote({
    keep_index <- which(.(xtick) %in% ANL[[.(xaxis)]])
    xtick <- (.(xtick))[keep_index] # extra parentheses needed for edge case, e.g. 1:5[keep_index]
    xlabel <- (.(xlabel))[keep_index]
  })
)

# Row 754
data = ANL[stats::complete.cases(ANL[, c(.(yaxis), .(xaxis))]), ],
```
**_tm_g_gh_spaghettiplot:_** doesn't do the subset 
```ruby
# Row 445-448
private_qenv <- teal.code::eval_code(
  object = private_qenv,
  code = bquote(xtick <- .(xtick))
)

# Row 472
data = ANL
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by npaszty** [comment] 2023-07-12 17:09
@gogonzo 
Can this enhancement request be picked up by the team. We're on the cusp of deploying a production app and was hoping to have this sorted.
let me know if a quick chat would facilitate. thanks!

**Comment by m7pr** [comment] 2023-07-19 12:00
Hi @feiyis1 and @npaszty . We have a proposition for fixing this issue in this PR https://github.com/insightsengineering/teal.goshawk/pull/227 We added a new input to `Plot Aesthetic Settings` foldable UI that allows to free the scales of axes, independently for X axis, Y axis or both axes at the same time. 

If you would provide the code of your app, I could test if that works for your example as well

**Comment by feiyis1** [comment] 2023-07-21 04:22
Hi @m7pr , thanks for your detailed proposition. Due to data permissions, you won't be able to run the code of our app if the code is provided. Can we pull your feature branch and test if you have one?

**Comment by m7pr** [comment] 2023-07-21 07:07
@feiyis1 yes, try `219_scales_for_spaghettiplot@main` branch at `teal.goshawk`, and prior to that reinstall `goshawk` from `main` branch

**Comment by m7pr** [comment] 2023-07-21 14:24
@feiyis1 you can actually install `teal.goshawk` from main.

**Comment by feiyis1** [comment] 2023-07-24 16:35
Hi @m7pr, I reinstalled the main branches of `goshawk` first and then `teal.goshawk` to our custom_R_libs (rather than use /opt/bee/share/nest-packages/2022_10_13/4.1.1/libs as the first libPath) using the following command:

```ruby
if (!require("remotes")) install.packages("remotes")
remotes::install_github("https://github.com/insightsengineering/goshawk.git”,  ref = “main”)
remotes::install_github("https://github.com/insightsengineering/teal.goshawk.git”,  ref = “main”)
```
But the **_Free X-axis scales_** feature in [#219 add facet_scales to plot aesthetics menu #227](https://github.com/insightsengineering/teal.goshawk/pull/227) isn't reflected in our app yet. Would like to double check if I reinstalled the main branches of these two packages as what you meant.

**Comment by npaszty** [comment] 2023-07-24 18:36
@feiyis1 

I believe you'd need to use the feature branch and rebuild the package from within the branch and then test the visualizartions.

**Comment by m7pr** [comment] 2023-07-26 11:02
@feiyis1 @npaszty main branch should be enough, as feature branch was deleted after the merge to `main`. What `goshawk` and `teal.goshawk` versions do you get when you run

```{R}
library(goshawk)
library(teal.goshawk)
packageVersion("goshawk")
packageVersion("teal.goshawk")
```

Do you get the same versions as on `main` branch?

https://github.com/insightsengineering/teal.goshawk/blob/5e9846f086316d789bd629cdaf8604005dc41ac5/DESCRIPTION#L4
https://github.com/insightsengineering/teal/blob/720a374771b296460f0eee9dabf00d4891f7c831/DESCRIPTION#L4

Lastly, you have weird brackets in your `ref` parameter

![image](https://github.com/insightsengineering/teal.goshawk/assets/133694481/8d237e23-ed32-4b9a-974a-2c53708c692c)

did the code work at all?

Try below

```{R}
if (!require("remotes")) install.packages("remotes")
remotes::install_github("insightsengineering/goshawk", force = TRUE)
remotes::install_github("insightsengineering/teal.goshawk", force = TRUE)
```

**Comment by npaszty** [comment] 2023-07-26 15:07
@m7pr 
didn't realize this had been merged before we had a chance to test.

**Comment by m7pr** [comment] 2023-07-26 15:37
Hey @npaszty I did test it on my own and also had help from @chlebowa during the review at hub.com/insightsengineering/teal.goshawk/pull/227 
We were pretty confident about the feature, as it was just an extension of one parameter for ggplot::facet_wrap, especially because testing took 2 days. 

I hope it did solve your needs. I managed to help @feiyis1 setup her session and saw that this new feature was available in her session.

**Comment by npaszty** [comment] 2023-07-27 00:36
@m7pr @feiyis1 

I reopened this issue after our testing. we're not crazy about the additional UI free-scale checkbox as it isn't intuitive to users. 

Feiyi included the line plot comparison when this issue was opened as an example of existing functionality that we would like for the spaghetti plot. it doesn't look like the geoms used in the two goshawk functions are different which isn't surprising since a line plot and spaghetti plot are essentially the same type of visualization. 

I think this issue might belong in the goshawk package and not teal.goshawk package. can you review the goshawk::g_lineplot and goshawk::g_spaghetti plot functions and bring the designs consistent to handle tics display with no data.

what is best for the user experience is to set the EPOCH filter and to not have to figure out why the filter didn't have the desired effect on the visualization. having to set the filter and then figure out to check the free-scale checkbox is not a desirable design.

thanks!

**Comment by m7pr** [comment] 2023-07-27 07:17
Hi @npaszty , even though both plots use `geom_line` they are not the same as `spaghettiplot` also uses `facet_wrap` that does not remove x-ticks if one of the corresponding datapoints exist, at least in one dimension, in any of the facetted plots. And that's the default behavior of facetted ggplot2 plots. We allowed to manipulate parameters to change the default behavior. I don't think it's beneficial to change the default behavior only because of one, tailored user request. If you need a customized behavior, it is possible to achieve, but changing defaults ways of plotting plots might cause that we will get another requests to bring this back. Having foreseen such polarized requests we allow for customization, but we keep default ggplot features to be applied on a startup.

**Comment by chlebowa** [comment] 2023-07-27 08:32
An alternative is to remove the checkbox and leave the choice up to the app developer.

**Comment by m7pr** [comment] 2023-07-27 09:03
Yes, you can edit your `app.R` file and set `free_x = TRUE` in `goshawk::g_spaghetti` call, so in your app you get that by default on a startup. Does that work?

**Comment by chlebowa** [comment] 2023-07-27 09:09
I mean a per-app setting, not a default start state that can be changed by the user.

**Comment by m7pr** [comment] 2023-07-27 09:11
So that is a per-app setting as it's gonna be `free_x = TRUE` only in your app. And by default it is `free_x = FALSE` which leaves the behavior as it was, before this card. UI is extended with a chechbox that allows you to move between states, even though some state was specified by the app developer on a startup

**Comment by chlebowa** [comment] 2023-07-27 09:20
There is no "you". There is the app user and the app developer. With a checkbox the decision is up to the user, without it it is up to the app dev.

**Comment by m7pr** [comment] 2023-07-27 09:31
Yeah that is clear. But ability to set it by app developer to TRUE and exposing it as a checked checkbox gives the most flexibility in this case and serves the purpose of not needing the check the box if no other options are needed now.

**Comment by npaszty** [comment] 2023-07-27 23:41
@m7pr 

thanks for highlighting the difference between the line and spaghetti plot despite using same geoms. non of the facets have data at the points that we'd like to not display so not sure why they are displayed in that case.

i'm confident in the testing the team does as you're all much better technically than I'd ever be. but what we bring to the table is the end user/stakeholder perspective in the business context and testing the updates from that vantage point is also quite helpful. looks like Feiyi opened another issue related to the topic so maybe we close this again and hop over to that issue?

**Comment by chlebowa** [comment] 2023-07-28 07:08
@npaszty could you link the new issue, please?

**Comment by m7pr** [comment] 2023-07-28 09:59
@npaszty I think a small change in your app.R in the place where you use `teal.goshawk::tm_g_gh_spaghettiplot` should solve the problem. In the place where you call `teal.goshawk::tm_g_gh_spaghettiplot` function, put there one new parameter `free_x = TRUE`. And then rerun the app to see the removal of NAs for facetted plots happening by default for you.

**Comment by npaszty** [comment] 2023-07-28 14:03
Doh!
Feiyi's other issue I saw in my email was on gitlab. sorry, not paying attention. 😢 
thanks for the suggestions. will checkin with her today.
have a good weekend.

**Comment by npaszty** [comment] 2023-07-28 22:04
@m7pr 
we did some additional testing and observed unexpected behavior.  so something going on in faceting context that we don't understand. perhaps we can setup a hangout next week and demo using our data mart data.

free scales TRUE, filtered ARM, filtered EPOCH and tics with no data continue to display.

![image](https://github.com/insightsengineering/teal.goshawk/assets/40777373/172201a4-3443-4a62-b5b8-a864223c5e28)

also tried using further filtering to remove visits but that didn't result in ticks being removed.
![image](https://github.com/insightsengineering/teal.goshawk/assets/40777373/23274724-d064-4be8-89f3-3824dcf6fab0)

**Comment by m7pr** [comment] 2023-07-30 18:01
Hi @npaszty . Thanks for the message. Unfortunately the quality of images is low and I can not see what is going on on the app you tried to share in those images. Can you reupload?

Also, what if you remove NAs (in the filter panel menu) from the variable that is used in X axis

**Comment by feiyis1** [comment] 2023-07-31 18:31
Hi @m7pr, I reuploaded the screenshot below. EPOCH = TREATMENT is unchecked in the filter panel. But the corresponding x ticks with no data highlighted in the red box continue to display.

![Screenshot 2023-07-31 at 8 56 27 AM](https://github.com/insightsengineering/teal.goshawk/assets/127898767/7007e96c-20df-4b99-bb19-5d0944a7346e)

To remove NAs in the filter panel menu, I checked [**Filter panel for developers**](https://insightsengineering.github.io/teal.slice/main/articles/filter-panel-for-developers.html#getting-and-setting-filter-states) documentation and set `keep_na = TRUE` or  `keep_na = FALSE` in  `teal_slice` function within `teal_slices` function as the following, but the "Keep NA" check box didn't show up in either case. Can you provide me with some further guidance? Thanks.

```ruby
  filter = teal_slices(
    teal_slice(dataname = "ADSL", varname = "SAFFL"),
    teal_slice(dataname = "ADLB", varname = "EPOCH", keep_na = TRUE)
  )
```

**Comment by m7pr** [comment] 2023-08-01 08:53
@feiyis1 thanks for the higher resolution - now it's better.
What you really want is `keep_na = FALSE` on `AVICITCDN` and `AVAL` as those are exposed on the plot axes. Let me know if that helps. I think this checkbox will appear only for variables that have NAs. It didn't pop up for EPOCHS as it looks like they do not have NAs, but I hope it will appear for `AVICITCDN` / `AVAL`

**Comment by chlebowa** [comment] 2023-08-01 09:14
I think what Marcin meant was to uncheck the "keep NAs" checkbox for the value that is plotted on the Y axis. X values for which there are no Y data **are** removed but X values for which there are missing values (NAs) are not.

Take a look at this:

![NAs_in](https://github.com/insightsengineering/teal.goshawk/assets/114988527/eaf8ad0c-7ddf-45e8-bc86-d54fd6ad37de)
![NAs_out](https://github.com/insightsengineering/teal.goshawk/assets/114988527/328ea2a5-a2c5-44c2-b6d9-15c7eec450e5)

**Comment by chlebowa** [comment] 2023-08-01 09:25
Ok, looking at you app again I am beginning to think we may have misunderstood the problem a little bit.

**Comment by chlebowa** [comment] 2023-08-01 09:39
I have two questions.
1. `EPOCH` is a factor variable, correct?
2. What version of `ggplot2` are you using?

**Comment by feiyis1** [comment] 2023-08-01 22:56
Hi @chlebowa , `EPOCH` is a factor variable. We are using `ggplot2` version 3.4.2.

Hi @m7pr , NAs of AVAL are filtered before the app runs: `ADLB_SUBSET0 <- readRDS(ADLB_path) %>% filter(!is.na(AVAL))`. `AVISITCDN` doesn’t have missingness with the same filters according to the **“View Variables”** table.
<img width="1482" alt="avisitcdn" src="https://github.com/insightsengineering/teal.goshawk/assets/127898767/a6dde21f-4825-492a-87a4-88d1eeced8b7">

In both `tm_g_gh_lineplot` and `tm_g_gh_spaghettiplot` functions, we passed two vectors into `xtick` and `xlabel` arguments. 
![x tick](https://github.com/insightsengineering/teal.goshawk/assets/127898767/8955763d-969b-4fe5-8847-29a5931ca75a)
![tick and label](https://github.com/insightsengineering/teal.goshawk/assets/127898767/c28406b8-9f05-4e64-aff4-1fb6b448b20d)
The line plot displays only necessary ticks based on the EPOCH filter. Given that the spaghetti plot has the facet feature, will the way we pass vectors to those two arguments be a potential cause of the redundant x ticks displaying issue?
![line plot](https://github.com/insightsengineering/teal.goshawk/assets/127898767/dafde454-fd7b-485e-8bc6-c9cc3646630f)

Happy to have a call if needed.

**Comment by chlebowa** [comment] 2023-08-02 15:04
@feiyis1 I think a call is in order, can you please schedule one for tomorrow or Monday?

**Comment by feiyis1** [comment] 2023-08-04 23:37
After taking @chlebowa's suggestion of turning the x variable `AVISITCDN` into a factor, the spaghetti plot works fine (i.e. when EPOCH = SCREENING and EPOCH = FOLLOW-UP are checked, TREATMENT weeks ticks no longer display). 

But when I also uncheck "Free X-Axis Scales" in the encoding panel, the spaghetti plot still works fine. Then it seems like this new feature designed by @m7pr becomes unnecessary if the app developer sets the x variable as a factor?

![spaghetti plot](https://github.com/insightsengineering/teal.goshawk/assets/127898767/b13d7e07-7db8-40c6-aaa7-ece611284ef9)

**Comment by feiyis1** [comment] 2023-08-08 15:40
Yeah, I saw your previous pull request testing this feature. Thanks @m7pr and @chlebowa for your help!

**Closed** 2023-08-09 07:53 UTC
Labels: enhancement, core
